### PR TITLE
V3

### PR DESCRIPTION
**Pull request by mbardelmeijer**
Add support for L9
Drop Laravel 8 & PHP 8.0 and lower
Cleanup

### CODE REVIEW

**Comment by mabdullahsari** [comment]
Hey @mbardelmeijer 

Any ETA on when this would be released?

Thanks!

**Comment by mbardelmeijer** [comment]
@mabdullahsari quite honestly forgot about this one. I'll make sure to check it today and release a 3.0. Thanks for the poke.

**Comment by mabdullahsari** [comment]
> @mabdullahsari quite honestly forgot about this one. I'll make sure to check it today and release a 3.0. Thanks for the poke.

No problem. I'm happy to contribute if you'd need it! Thanks for the rapid response 🙏

**Comment by mbardelmeijer** [comment]
@mpociot could you perhaps (if you're still attached to the `laravel-notification-channels` project) disable StyleCI & Scrutinizer on this repo? We've moved to `php-cs-fixer` (and possibly Laravel Pint in the future).

**Comment by mbardelmeijer** [comment]
@mabdullahsari done and tagged!

**Pull request merged**
